name: Update Albums

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      # Depedencies
      - uses: actions/checkout@v3

      # Fetch
      - name: Fetch photo album
        run: |
          mkdir output
          curl \
            -H 'Accept: application/json' \
            https://photo-portfolio-amber.vercel.app/api/TzQSCHMmkXxycPxi9 \
            -o output/album.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          # Produced by getJarvisDiag.sh
          path: ./public/album-data
          if-no-files-found: ignore

      - name: Generate Github summary
        shell: bash
        run: |
          echo "Creating Github Action summary..."
          echo "$(ls ./public/album-data)" >> $GITHUB_STEP_SUMMARY
